### ISSUE TITLE
Interdire aux éléments de sortir de l'image

### ISSUE THREAD

**Issue by ipante** [VittoGCM/Demographie_Suisse_Cantons#2]
Actuellement, il est possible de voir certains éléments sortir du cadre. Il faudrait voir comment éviter que cela arrive (il est en effet impossible de récupérer les cantons à partir de ce point.

**Comment by lohaaaa** [comment]
Nous n'avons pas trouvé comment interdire aux éléments de sortir du cadre. Cependant, nous leurs avons appliqué une force supplémentaires pour que ces derniers reviennent toujours au centre après avoir été déplacés.
