### ISSUE TITLE
Amplifier le projet

### ISSUE THREAD

**Issue by ipante** [VittoGCM/Demographie_Suisse_Cantons#5]
Pour trois personnes, le projet est beaucoup trop léger. Il faut absolument l'amplifier d'une manière ou d'une autre. Vous pourriez notamment :

- proposer plusieurs années de données
- proposer d'autres visualisations de ces mêmes données

**Comment by VittoGCM** [comment]
Nouvelles améliorations du projet - il est désormais composé de 3 visualisations et le projet est moins brouillon.
